# Generated by Django 2.2.5 on 2019-11-11 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_trainer_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=55, unique=True)),
                ('overview', models.TextField()),
                ('details', models.TextField()),
                ('material_1', models.TextField()),
                ('material_2', models.TextField(blank=True, null=True)),
                ('material_3', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignedchallengestoclient',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='assignedchallengestoclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='challengedactivities',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='challengedactivities',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='certification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='locations_served',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='AssignedChallengesToClient',
        ),
        migrations.DeleteModel(
            name='ChallengedActivities',
        ),
        migrations.DeleteModel(
            name='Challenges',
        ),
        migrations.AddField(
            model_name='program',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Trainer'),
        ),
    ]
