dist: bionic
language: python
python:
    - "3.6"

services:
    - docker

# Install dependency
before_install:
    - sudo apt-get update
    - sudo apt-get -y install docker-compose

before_script:
    - sudo docker-compose build
    - sudo docker-compose run app python3 fitness-portal/manage.py makemigrations portal
    - sudo docker-compose run app python3 fitness-portal/manage.py migrate

script:
    - sudo docker-compose run app python3 fitness-portal/manage.py test tests

