dist: bionic
language: python
python:
    - "3.6"

services:
    - mysql

env:
    -DJANGO=2.2 DB=mysql
install:
    - pip install -r docker/requirements.txt

before_script:
    - mysql -e 'create database test;' -u root

script:
    - python3 fitness-portal/manage.py test tests

